import type { IntegrationProviderDefinition } from "./types";

export const integrationProviders = [
  {
    id: "ke-etims",
    name: "Kenya eTIMS/KRA",
    category: "tax",
    region: "KE",
    phase: 1,
    approvalRequired: true,
    env: [
      { key: "KRA_ETIMS_ENVIRONMENT", label: "Environment", requiredForLive: true },
      { key: "KRA_ETIMS_BASE_URL", label: "Base URL", requiredForLive: true },
      { key: "KRA_ETIMS_CLIENT_ID", label: "Client ID", requiredForLive: true },
      { key: "KRA_ETIMS_CLIENT_SECRET", label: "Client secret", requiredForLive: true },
      { key: "KRA_ETIMS_WEBHOOK_SECRET", label: "Webhook secret", requiredForLive: false },
    ],
    localFoundation:
      "Taxpayer profiles, rental returns, tax charges, eTIMS-ready receipts, sales payload builder, OAuth token client, webhook at /api/webhooks/kra-etims.",
    nextAction:
      "Set KRA_ETIMS_* env (CLIENT_ID, CLIENT_SECRET, ENVIRONMENT, CU_SERIAL, BASE_URL) and complete KRA device/OSCU onboarding for live CU signatures.",
  },
  {
    id: "ke-mpesa-daraja",
    name: "M-Pesa Daraja STK",
    category: "payments",
    region: "KE",
    phase: 1,
    approvalRequired: true,
    env: [
      { key: "MPESA_ENVIRONMENT", label: "Environment", requiredForLive: true },
      { key: "MPESA_CONSUMER_KEY", label: "Consumer key", requiredForLive: true },
      { key: "MPESA_CONSUMER_SECRET", label: "Consumer secret", requiredForLive: true },
      { key: "MPESA_SHORTCODE", label: "Shortcode", requiredForLive: true },
      { key: "MPESA_PASSKEY", label: "Passkey", requiredForLive: true },
      { key: "MPESA_CALLBACK_URL", label: "Callback URL", requiredForLive: true },
      { key: "MPESA_CALLBACK_SECRET", label: "Callback secret", requiredForLive: true },
    ],
    localFoundation: "Payment records, checkout IDs, callbacks, tenant ledgers.",
    nextAction: "Activate Daraja app credentials and replace STK stub with live adapter.",
  },
  {
    id: "ke-kcb-buni-ipn",
    name: "KCB Buni Instant Payment Notification",
    category: "payments",
    region: "KE",
    phase: 1,
    approvalRequired: true,
    env: [
      { key: "KCB_BUNI_ENVIRONMENT", label: "Environment (uat|production)", requiredForLive: true },
      {
        key: "KCB_BUNI_IPN_SIGNATURE_SECRET",
        label: "IPN signature secret",
        requiredForLive: true,
      },
      {
        key: "KCB_BUNI_IPN_CALLBACK_URL",
        label: "Public callback URL registered with KCB",
        requiredForLive: true,
      },
    ],
    localFoundation:
      "Org KCB paybill/account methods, pending BANK payments, webhook matching, org verification + receipts.",
    nextAction:
      "Register HTTPS callback with buni@kcbgroup.com and set KCB_BUNI_IPN_SIGNATURE_SECRET from Buni docs.",
  },
  {
    id: "ae-aani",
    name: "UAE Aani/instant payments",
    category: "payments",
    region: "AE",
    phase: 1,
    approvalRequired: true,
    env: [
      { key: "AANI_BASE_URL", label: "Base URL", requiredForLive: true },
      { key: "AANI_CLIENT_ID", label: "Client ID", requiredForLive: true },
      { key: "AANI_CLIENT_SECRET", label: "Client secret", requiredForLive: true },
      { key: "AANI_WEBHOOK_SECRET", label: "Webhook secret", requiredForLive: true },
    ],
    localFoundation: "Generic payment lifecycle can store external references and callbacks.",
    nextAction: "Secure UAE payment partner access and define tenant checkout flow.",
  },
  {
    id: "multi-currency-ledgers",
    name: "Multi-currency ledgers",
    category: "ledger",
    region: "GLOBAL",
    phase: 1,
    approvalRequired: false,
    env: [
      { key: "FX_PROVIDER", label: "FX provider", requiredForLive: true },
      { key: "FX_API_KEY", label: "FX API key", requiredForLive: true },
    ],
    localFoundation: "Organization currency, payment amounts, report exports.",
    nextAction: "Add currency columns to ledger events before enabling wallet custody.",
  },
  {
    id: "ae-dld-ejari",
    name: "Dubai DLD/Ejari",
    category: "government",
    region: "AE",
    phase: 1,
    approvalRequired: true,
    env: [
      { key: "DLD_EJARI_BASE_URL", label: "Base URL", requiredForLive: true },
      { key: "DLD_EJARI_CLIENT_ID", label: "Client ID", requiredForLive: true },
      { key: "DLD_EJARI_CLIENT_SECRET", label: "Client secret", requiredForLive: true },
    ],
    localFoundation: "Lease records and contract document assets.",
    nextAction: "Confirm DLD/Ejari API program requirements and legal payload fields.",
  },
  {
    id: "bank-reconciliation",
    name: "Bank API reconciliation",
    category: "banking",
    region: "EA",
    phase: 1,
    approvalRequired: true,
    env: [
      { key: "BANKING_AGGREGATOR", label: "Aggregator", requiredForLive: true },
      { key: "BANKING_CLIENT_ID", label: "Client ID", requiredForLive: true },
      { key: "BANKING_CLIENT_SECRET", label: "Client secret", requiredForLive: true },
      { key: "BANKING_WEBHOOK_SECRET", label: "Webhook secret", requiredForLive: false },
    ],
    localFoundation: "Payment reconciliation status, notes, and manual report exports.",
    nextAction: "Select bank/aggregator path, then connect statement matching jobs.",
  },
  {
    id: "tenant-screening",
    name: "CRB/AECB screening",
    category: "screening",
    region: "GLOBAL",
    phase: 1,
    approvalRequired: true,
    env: [
      { key: "SCREENING_PROVIDER", label: "Screening provider", requiredForLive: true },
      { key: "SCREENING_API_KEY", label: "API key", requiredForLive: true },
      { key: "AECB_CLIENT_ID", label: "AECB client ID", requiredForLive: false },
      { key: "AECB_CLIENT_SECRET", label: "AECB client secret", requiredForLive: false },
    ],
    localFoundation: "Tenant identity fields, history records, verification workflow.",
    nextAction: "Finalize consent language and provider-specific identity matching.",
  },
  {
    id: "whatsapp-agent",
    name: "WhatsApp AI assistant",
    category: "messaging",
    region: "GLOBAL",
    phase: 1,
    approvalRequired: false,
    env: [
      { key: "WHATSAPP_PHONE_NUMBER_ID", label: "Phone number ID", requiredForLive: true },
      { key: "WHATSAPP_ACCESS_TOKEN", label: "Access token", requiredForLive: true },
      { key: "WHATSAPP_VERIFY_TOKEN", label: "Verify token", requiredForLive: false },
      { key: "AI_ASSISTANT_PROVIDER", label: "AI provider", requiredForLive: false },
      { key: "AI_ASSISTANT_API_KEY", label: "AI API key", requiredForLive: false },
    ],
    localFoundation: "Notification queue, WhatsApp sender, tenant issues and payments.",
    nextAction: "Add inbound webhook routing and policy-controlled assistant actions.",
  },
  {
    id: "vendor-escrow-marketplace",
    name: "Vendor escrow marketplace",
    category: "maintenance",
    region: "GLOBAL",
    phase: 2,
    approvalRequired: true,
    env: [
      { key: "ESCROW_PROVIDER", label: "Escrow provider", requiredForLive: true },
      { key: "ESCROW_API_KEY", label: "API key", requiredForLive: true },
    ],
    localFoundation: "Issue tickets, caretaker assignments, payment records.",
    nextAction: "Choose licensed escrow/payment partner before holding funds.",
  },
  {
    id: "e-lease-signatures",
    name: "Multi-market e-leases",
    category: "leasing",
    region: "GLOBAL",
    phase: 2,
    approvalRequired: false,
    env: [
      { key: "E_SIGNATURE_PROVIDER", label: "Signature provider", requiredForLive: true },
      { key: "E_SIGNATURE_API_KEY", label: "API key", requiredForLive: true },
    ],
    localFoundation: "Lease data and contract document storage.",
    nextAction: "Add jurisdiction templates and signature evidence envelopes.",
  },
  {
    id: "dynamic-pricing",
    name: "Hyper-local rent pricing",
    category: "pricing",
    region: "GLOBAL",
    phase: 3,
    approvalRequired: false,
    env: [
      { key: "MARKET_DATA_PROVIDER", label: "Market data provider", requiredForLive: true },
      { key: "MARKET_DATA_API_KEY", label: "API key", requiredForLive: true },
    ],
    localFoundation: "Vacancy pages, unit rent fields, property locations.",
    nextAction: "Use licensed market feeds before any scraping-based automation.",
  },
  {
    id: "fractional-investment",
    name: "Fractional real estate investment",
    category: "investment",
    region: "GLOBAL",
    phase: 4,
    approvalRequired: true,
    env: [
      { key: "INVESTMENT_COMPLIANCE_PROVIDER", label: "Compliance provider", requiredForLive: true },
      { key: "KYC_AML_PROVIDER", label: "KYC/AML provider", requiredForLive: true },
    ],
    localFoundation: "None yet beyond property records and audit logs.",
    nextAction: "Treat as a regulated product with legal, KYC/AML, and securities review.",
  },
] as const satisfies IntegrationProviderDefinition[];
