import {
  HiOutlineBell,
  HiOutlineCalendarDays,
  HiOutlineCreditCard,
  HiOutlineDocumentText,
  HiOutlineFolder,
  HiOutlineHome,
  HiOutlineReceiptRefund,
  HiOutlineShieldCheck,
  HiOutlineUser,
  HiOutlineWrenchScrewdriver,
  HiOutlineClipboardDocumentList,
} from "react-icons/hi2";

export const tenantNavItems = [
  { label: "Dashboard", href: "/dashboard/tenant", icon: HiOutlineHome, emoji: "🏠", requiresActiveLease: false },
  { label: "Profile", href: "/dashboard/tenant/profile", icon: HiOutlineUser, emoji: "👤", requiresActiveLease: false },
  { label: "Security", href: "/dashboard/security", icon: HiOutlineShieldCheck, emoji: "🔐", requiresActiveLease: false },
  { label: "Lease", href: "/dashboard/tenant/lease", icon: HiOutlineDocumentText, emoji: "📄", requiresActiveLease: true },
  { label: "Payments", href: "/dashboard/tenant/payments", icon: HiOutlineCreditCard, emoji: "💳", requiresActiveLease: true },
  { label: "Invoices", href: "/dashboard/tenant/invoice", icon: HiOutlineReceiptRefund, emoji: "🧾", requiresActiveLease: true },
  { label: "Expenditures", href: "/dashboard/tenant/expenditures", icon: HiOutlineReceiptRefund, emoji: "💸", requiresActiveLease: true },
  { label: "Water Bills", href: "/dashboard/tenant/water-bills", icon: HiOutlineClipboardDocumentList, emoji: "💧", requiresActiveLease: true },
  { label: "Issues", href: "/dashboard/tenant/issues", icon: HiOutlineWrenchScrewdriver, emoji: "🛠️", requiresActiveLease: true },
  { label: "Maintenance", href: "/dashboard/tenant/maintenance", icon: HiOutlineWrenchScrewdriver, emoji: "🔧", requiresActiveLease: true },
  { label: "Inspections", href: "/dashboard/tenant/inspections", icon: HiOutlineCalendarDays, emoji: "🗓️", requiresActiveLease: true },
  { label: "Notices", href: "/dashboard/tenant/notices", icon: HiOutlineBell, emoji: "🔔", requiresActiveLease: true },
  { label: "Notifications", href: "/tenants/notifications", icon: HiOutlineBell, emoji: "📬", requiresActiveLease: true },
  { label: "Documents", href: "/dashboard/tenant/documents", icon: HiOutlineFolder, emoji: "📁", requiresActiveLease: true },
] as const;
