export const APP_PLANS = {
  FREE: {
    name: "Free",
    badge: "Start",
    monthlyAmount: 0,
    propertiesLimit: 1,
    unitsLimit: 10,
    usersLimit: 2,
    description:
      "For small landlords testing structured property records before scaling operations.",
    cta: "Start free",
    href: "/register",
    included: [
      "1 property",
      "Up to 10 units",
      "2 internal users",
      "Tenant profiles",
      "Unit occupancy tracking",
      "Basic lease records",
      "Manual payment records",
      "Basic dashboard overview",
    ],
    excluded: [
      "Advanced reports",
      "Caretaker workflows",
      "Move-out inspections",
      "Data exports",
      "Priority support",
    ],
  },
  PRO: {
    name: "Pro",
    badge: "Popular",
    monthlyAmount: 4500,
    propertiesLimit: 5,
    unitsLimit: 100,
    usersLimit: 8,
    description:
      "For active property teams managing billing, tenants, payments, and daily follow-up.",
    cta: "Choose Pro",
    href: "/register?plan=pro",
    included: [
      "Up to 5 properties",
      "Up to 100 units",
      "Up to 8 internal users",
      "Everything in Free",
      "Rent and balance tracking",
      "Water billing workflows",
      "Payment verification",
      "Paid vs unpaid tenant reports",
      "Tenant payment ratings",
      "Notifications and reminders",
      "Issue ticket handling",
    ],
    excluded: [
      "Advanced caretaker assignment controls",
      "Move-out inspection closeout",
      "Bulk data exports",
      "Custom onboarding",
    ],
  },
  PLUS: {
    name: "Plus",
    badge: "Growth",
    monthlyAmount: 9500,
    propertiesLimit: 20,
    unitsLimit: 500,
    usersLimit: 25,
    description:
      "For growing portfolios that need staff coordination, reports, inspections, and controls.",
    cta: "Choose Plus",
    href: "/register?plan=plus",
    included: [
      "Up to 20 properties",
      "Up to 500 units",
      "Up to 25 internal users",
      "Everything in Pro",
      "Caretaker assignments",
      "Move-out notices and inspections",
      "Tenant history after move-out",
      "Profile transfer workflow support",
      "Advanced operational reports",
      "Audit visibility",
      "Data export requests",
      "Priority support",
    ],
    excluded: ["Custom infrastructure support", "Dedicated rollout manager"],
  },
  ENTERPRISE: {
    name: "Custom",
    badge: "Scale",
    monthlyAmount: 0,
    propertiesLimit: Number.MAX_SAFE_INTEGER,
    unitsLimit: Number.MAX_SAFE_INTEGER,
    usersLimit: Number.MAX_SAFE_INTEGER,
    description:
      "For large organizations that need tailored limits, rollout planning, governance, and support.",
    cta: "Contact sales",
    href: "/contact",
    included: [
      "Unlimited properties",
      "Unlimited units",
      "Unlimited internal users",
      "Everything in Plus",
      "Custom limits and billing terms",
      "Dedicated implementation support",
      "Governance and permission planning",
      "Custom reporting guidance",
      "Bulk migration support",
      "Priority incident handling",
      "Enterprise support reviews",
    ],
    excluded: [],
  },
} as const;

export type AppPlan = keyof typeof APP_PLANS;

export const APP_PLAN_ORDER = ["FREE", "PRO", "PLUS", "ENTERPRISE"] as const;
