import { writeFileSync } from "node:fs";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { WORKSPACE_ICONS } from "../apps/web/src/components/shared/workspace-icon";

// Keep CSS heading/metric masks identical to the SVG components used in navigation.
const masks = Object.fromEntries(Object.entries(WORKSPACE_ICONS).map(([name, Icon]) => {
  const svg = renderToStaticMarkup(createElement(Icon, { stroke: "black", strokeWidth: 1.75 }));
  return [name, `url("data:image/svg+xml,${encodeURIComponent(svg)}")`];
}));
writeFileSync(new URL("../apps/web/src/components/shared/workspace-icon-masks.ts", import.meta.url),
  `// Generated by scripts/generate-workspace-icon-masks.ts. Do not edit by hand.\nexport const workspaceIconMasks = ${JSON.stringify(masks, null, 2)};\n`);
