import Link from "next/link";
import { Clock3, Download, FileSpreadsheet } from "lucide-react";
import { ORG_REPORT_EXPORTS } from "@/lib/reports/org-report-exports";
import type { ReportsPageData } from "../_lib/types";

export function ReportsExportsSection({ data }: { data: ReportsPageData }) {
  return (
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]">
      <section className="overflow-hidden rounded-3xl border border-border bg-card text-card-foreground shadow-sm">
        <div className="flex flex-col gap-3 border-b border-border px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6">
          <div>
            <p className="text-sm font-semibold text-foreground">Export report pack</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Download CSV files for finance review, owner updates, and migration archives.
            </p>
          </div>
        </div>

        <div className="grid gap-3 p-5 sm:grid-cols-2 sm:p-6">
          {ORG_REPORT_EXPORTS.map((item) => (
            <Link
              key={item.kind}
              href={`/api/org/reports/export?type=${item.kind}&period=${data.period}`}
              title={item.description}
              className="group rounded-2xl border border-border bg-background p-4 transition hover:border-primary/40 hover:bg-muted/15"
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-sm font-semibold text-foreground">{item.label}</p>
                  <p className="mt-2 text-sm leading-6 text-muted-foreground">
                    {item.description}
                  </p>
                </div>
                <span className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-border bg-muted/20 text-muted-foreground transition group-hover:border-primary/30 group-hover:text-primary">
                  <Download className="h-4 w-4" />
                </span>
              </div>
            </Link>
          ))}
        </div>
      </section>

      <section className="overflow-hidden rounded-3xl border border-border bg-card text-card-foreground shadow-sm">
        <div className="flex flex-col gap-3 border-b border-border px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6">
          <div>
            <p className="text-sm font-semibold text-foreground">Report archive</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Recent report downloads generated by this organization.
            </p>
          </div>
          <span className="inline-flex w-fit items-center gap-2 rounded-full border border-border bg-muted/20 px-3 py-1 text-xs font-semibold text-muted-foreground">
            <Clock3 className="h-3.5 w-3.5" />
            {data.recentExports.length} recent
          </span>
        </div>

        <div className="space-y-3 p-5 sm:p-6">
          {data.recentExports.map((item) => (
            <div
              key={item.id}
              className="rounded-2xl border border-border bg-muted/10 p-4"
            >
              <p className="truncate text-sm font-semibold text-foreground">
                {item.reportType}
              </p>
              <p className="mt-1 truncate text-xs text-muted-foreground">{item.fileName}</p>
              <p className="mt-2 text-xs text-muted-foreground">
                {item.period ?? "Current"} •{" "}
                {item.createdAt.toLocaleString("en-KE", {
                  dateStyle: "medium",
                  timeStyle: "short",
                })}
              </p>
            </div>
          ))}

          {data.recentExports.length === 0 ? (
            <div className="flex flex-col items-center rounded-2xl border border-dashed border-border px-4 py-10 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-border bg-muted/20">
                <FileSpreadsheet className="h-5 w-5 text-muted-foreground" />
              </div>
              <p className="mt-4 text-sm font-semibold text-foreground">No report exports yet</p>
              <p className="mt-2 max-w-xs text-sm leading-6 text-muted-foreground">
                Download a report pack above and your export history will appear here.
              </p>
            </div>
          ) : null}
        </div>
      </section>
    </div>
  );
}